Updated TableVerificationSteps for the verifyColumnExists method to V…
dougnoel/sentinel pull request #389
Opened 2022-07-15 20:58 UTC by plmlkrz

Updated TableVerificationSteps for the verifyColumnExists method to Verify the given table does not contain the given column.  Added new tests in the Table Tests.feature file to test the does not contain option.

2022-07-18 16:05 UTC, sampacos approved these changes
I approve the changes but I think the behavior of Table.verifyColumnExists() needs to be reviewed. Currently it allows for partial matches of table headers, which I'm not sure I agree with.

2022-07-27 18:43 UTC, dougnoel requested changes

2022-07-27 18:43 UTC, dougnoel commented on src/main/java/com/dougnoel/sentinel/steps/TableVerificationSteps.java
> +    @Then("^I verify the (.*?)( does not)? contains? (?:a|the) (.*?) column$")
Let's modify this to do a has or a contains like other text steps. has is an equal, contains is a contains.

2022-07-27 18:49 UTC, dougnoel commented on src/main/java/com/dougnoel/sentinel/steps/TableVerificationSteps.java
> +    @Then("^I verify the (.*?)( does not)? contains? (?:a|the) (.*?) column$")
```suggestion
    @Then("^I verify the (.*?)( does not)? (contains?|has|have) (?:a|the) (.*?) column$")
```

2022-09-29 18:28 UTC, sampacos approved these changes

2022-09-30 15:31 UTC, dougnoel approved these changes

2022-09-30 15:31 UTC, merged