add support to use stored variables in APISteps params and header
dougnoel/sentinel pull request #501
Opened 2023-02-17 10:42 UTC by david-ondrus

add support to use stored variables in request body

2023-03-06 15:41 UTC, pturchinetz commented on src/main/java/com/dougnoel/sentinel/strings/SentinelStringUtils.java
> +	public static String replaceURLVariable(String text) {
needs header

2023-03-06 22:16 UTC, sampacos requested changes

2023-03-06 22:16 UTC, sampacos commented on src/main/java/com/dougnoel/sentinel/strings/SentinelStringUtils.java
> +	public static String replaceStoredVariables(String text) {
If I'm honest I don't like the design of the replacement syntax. If you need to surround something with quotes, why not just have the quotes in the template? For example, if you need the result to look like `"name": "Dog"`, why not make the input `"name": "{category_name}"`. It seems to me that's the only distinction made between `int` and `str` here, but I think it makes more sense to not have any such distinction. If there is a question of whether `{variable_name}` is unique enough, then we can change the syntax to something more unique without adding type info to the front.

2023-03-07 14:33 UTC, dougnoel commented on src/main/java/com/dougnoel/sentinel/steps/APISteps.java
> +		var endpointFormatted = SentinelStringUtils.replaceStoredVariables(endpoint);
This should be inline to be consistent with other usages.

2023-03-07 14:37 UTC, dougnoel commented on src/main/java/com/dougnoel/sentinel/steps/APISteps.java
> +	@Given("I set the request body with variables to")
I don't know what this step means. The steps need to read like manual testing steps. If this test were to fail and I were to have to manually reproduce this, what would the step look like to reproduce what's happening here? There are also no usage examples in the Javadoc above. If this is an internal helper method, there should be no Given decorator, and this method should be private.

2023-03-08 14:42 UTC, dougnoel commented on src/test/java/features/89 API Testing.feature
> +    When I initialize the data
When I initialize the configuration values as follows
"""
id: 10
category_name: puppies
"""

2023-03-08 18:36 UTC, dougnoel submitted a review, later dismissed

2023-03-08 20:31 UTC, pturchinetz approved these changes

2023-03-08 20:31 UTC, merged